### ISSUE TITLE
Integrate Caching into Volley Framework

### ISSUE THREAD

**Issue by sabre1041** [sabre1041/openshift-android#11]
Swap out existing Cache implementation and integrate with Google Volley framework.
- Google Volley utilizes HTTP Response Headers to define the Caching lifecycle based on whether the server returns an "Expires" or "max-age" value. OpenShift does not return these values.

**Comment by jyore** [comment]
Caching has been updated. There are two TTLs that are hard coded right now but I feel should be tuned and probably configurable.
- soft TTL (3min): This is the time the entry lives in memory. The request data gets updated on request after this expires
- TTL (24min): The time the cached data lives on the disk. Requires a request to popluate the page after expired

Things to do:
- Figure out how manually invalidate an entry before making a call.  This will be useful when someone makes some user operation, such as starting/stopping a server, so that the up/down status will update without having to wait for the soft TTL to expire

**Comment by jyore** [comment]
also need to make sure the cached information invalidates on logout

**Comment by jyore** [comment]
Caching appears to be working. closing issue
